# Generated by Django 3.2.4 on 2021-06-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch_downloader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Clip',
        ),
    ]
