# Generated by Django 3.2.4 on 2021-07-16 04:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twitch_downloader', '0002_auto_20210628_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('views', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('twitch_url', models.URLField(max_length=300)),
                ('local_url', models.URLField(max_length=300)),
                ('author', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.DeleteModel(
            name='TwitchAPI',
        ),
        migrations.AlterField(
            model_name='broadcaster',
            name='broadcaster_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='clip',
            name='broadcaster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitch_downloader.broadcaster'),
        ),
        migrations.AddField(
            model_name='clip',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitch_downloader.game'),
        ),
    ]
